### ISSUE TITLE
Unnecessary unwrap ?

### ISSUE THREAD

**Issue by hanako-eo** [jonhoo/atone#16]
When I navigate in the code I see in the method in `CustomVc` at the line 235 in lib.rs
```rs
    pub fn last(&self) -> Option<&T> {
        let len = self.len();
        if len == 0 {
            None
        } else {
            Some(self.get(len - 1).unwrap())
        }
    }
```

but why all of that ? You can just write
```rs
pub fn last(&self) -> Option<&T> {
    let len = self.len();
    if len == 0 {
        None
    } else {
        self.get(len - 1)
    }
}
```

(and same thing with the last_mut)

**Comment by jonhoo** [comment]
Ah, it is written this way essentially to be defensive — the get _should not fail_. If the code was written the way you propose, then it could _silently_ start failing if, say, the `len == 0` clause was changed somehow. In this small code snippet the risk of that is pretty minor, but as a general rule I like the more verbose variant because it represents an asset.
